---
name: Codecov badges
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  codecov:
    name: checkout branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install 
      - run: npm install
      - name: run tests
      - run: npx jest
      - name: upload codecov
      - run: codecov/codecov-action@v1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
        token: ${{ secrets.CODECOV_TOKEN }}